[package]
name = "memrepr"
authors = ["Peter Jin <peterhaijin@gmail.com>"]
version = "0.0.0"
edition = "2018"

[lib]
name = "memrepr"
path = "src/lib.rs"

[features]
default = []
f16 = ["half"]

[dependencies]
#float = { version = "*", optional = true }
half = { version = "^1.3", optional = true }
