[package]
name = "podmem"
authors = ["Peter Jin <peterhaijin@gmail.com>"]
version = "0.1.0-devel"
edition = "2018"

[features]
default = ["std"]
f16 = ["half"]
std = []

[dependencies]
#float = { version = "*", optional = true }
half = { version = "^1.3", optional = true }
